site_name: Learn Terraform
nav:
    - Home: index.md
    - Install: install.md
    - State: state.md
    - Syntax: syntax.md
    - Making a VPC:
      - AWS: aws-vpc.md
      - GCP: gcp-vpc.md
    - Creating a Subnet: subnet.md
    - Creating an Instance: instance.md
    - Autoscaling: autoscaling.md
    - Load Balancing:
      - Application: alb.md
    - Databases: 
      - RDS: rds.md
    - Storage:
      - S3: s3.md
    - IAM:
      - AWS: aws-iam.md
      - GCP: gcp-iam.md
    - DNS:
      - AWS: aws-dns.md
    - Advanced State: adv-state.md
    - Creating Modules: module.md
    - Help: help.md
    - About: about.md
theme: 
  name: material
  favicon: 'assets/images/favicon.ico'
repo_name: 'jamesWoolfenden/learn-packer-web'
repo_url: 'https://github.com/jamesWoolfenden/learn-terraform-web'
markdown_extensions:
  - admonition
  - codehilite
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Customization
extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'twitter'
      link: 'https://twitter.com/slalom'
    - type: 'linkedin'
      link: 'https://linkedin.com/company/slalom-consulting/'

# Copyright
copyright: 'Copyright &copy; 2019 - 2019 Slalom, LLC'
site_author: 'James Woolfenden'