---
# yamllint disable rule:indentation
site_name: Learn Terraform
nav:
  - Home: index.md
  - Examples: examples.md
  - Install: install.md
  - State: state.md
  - Syntax: syntax.md
  - Providers:
      - Utilities:
          - Local file: local_file.md
          - Template: template.md
          - Random: random.md
          - Terraform: terraform.md
          - TLS: tls.md
          - DNS: dns.md
          - Null: null.md
      - Status Cake: statuscake.md
      - Pager Duty: pagerduty.md
      - Docker: docker.md
      - Github: github.md
      - Gitlab: gitlab.md
      - Consul: consul.md
      - Vault: vault.md
  - Making a VPC:
      - AWS: aws-vpc.md
      - GCP: gcp-vpc.md
  - Creating a Subnet:
      - AWS: aws-subnet.md
  - Creating an Instance:
      - AWS: aws-instance.md
  - Autoscaling:
      - AWS: aws-autoscaling.md
  - Load Balancing:
      - AWS:
          - Application: aws-alb.md
  - Databases:
      - RDS: aws-rds.md
      - CloudSQL: gcp-cloudsql.md
  - Storage:
      - S3: aws-s3.md
      - Cloud Storage: gcp-cloudstorage.md
  - IAM:
      - AWS: aws-iam.md
      - GCP: gcp-iam.md
  - DNS:
      - Route 53: aws-dns.md
      - gcp: gcp-dns.md
  - Advanced State: adv-state.md
  - Structure: control.md
  - Modules:
      - Creating: module.md
      - Github Actions: github-actions.md
  - SourceCode:
      - CodeCommit: aws-codecommit.md
  - Containers:
      - AWS:
          - ECR: aws-ecr.md
          - ECS: aws-ecs.md
      - GCP:
          - GKE: gcp-kubernetes.md
  - Logging:
      - Cloudwatch: aws-cloudwatch.md
  - Workspaces: workspaces.md
  - Terraform cloud: tfe.md
  - Extending: extending.md
  - Failings: failings.md
  - Style Guide: style-guide.md
  - Help: help.md
  - About: about.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
  favicon: "assets/images/favicon.ico"
repo_name: "jamesWoolfenden/learn-terraform"
repo_url: "https://github.com/jamesWoolfenden/learn-terraform"
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: true
  - def_list
  - footnotes
  - md_in_html
  - meta
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# plugins
plugins:
  - search
  - minify:
      minify_html: true
  - mkdocs-add-teaser:
      teaser_class: "teaser"
# Customization
extra:
  manifest: "manifest.webmanifest"
  social:
    - icon: fontawesome/brands/github-alt
      link: "https://github.com/jameswoolfenden"
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/JimWoolfenden"
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/jameswoolfenden/"

# Copyright
copyright: "Copyright &copy; 2019 - 2021 James Woolfenden"
site_author: "James Woolfenden"
google_analytics:
  ["UA-151885688-1", "jameswoolfenden.github.io/learn-terraform/"]
