site_name: Learn Terraform
nav:
    - Home: index.md
    - Install: install.md
    - State: state.md
    - Syntax: syntax.md
    - Help: help.md
    - About: about.md
theme: material
markdown_extensions:
  - admonition
  - codehilite
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde